version: "3.4"
services:
  postgres:
    image: postgres:12.2
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
    ports:
      - "5432:5432"
    volumes:
      - ./db/backup:/backup
  adminer:
    image: adminer
    ports:
      - 8081:8080